### ISSUE TITLE
Not working with VSCode 1.31

### ISSUE THREAD

**Issue by yhc44** [shanalikhan/code-settings-sync#762]
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version :** [ 1.31 ] 
🌴 **Code Settings Sync Version :** [ 2.3.4 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ Mac OS High Sierra ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]

📰 **To Reproduce**
1. Update VSCode to 1.31
2. Start VSCode
3. See error

💪 **Expected behavior**
Working like it does all time.

📺 **Console Error Log** 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/yannheeser/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/yannheeser/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

📺  **Additional context**

"Extension host terminated unexpectedly"

**Comment by JM-Mendez** [comment]
I was able to get it working by uninstalling `fs-extra` and `fs-events` from my global `node_modules`.

**Comment by dapetrov0** [comment]
I can confirm that it's not working with 1.31

**Comment by shanalikhan** [comment]
you are all using Mac ? of not please write the details.


 **Code Settings Sync Version :** [ 2.3.4 ]
 **Standard or Insiders :** [ Standard ]
 **OSS or Portable :** [ OSS ]
 **Operating System :** [ Mac OS High Sierra ]

**Comment by mbinkhorst** [comment]
Can confirm.
**Code Settings Sync Version :** [ 3.2.4 ]
**Standard or Insiders :** [ Standard 1.31.0]
**OSS or Portable :** [ OSS ]
**Operating System :** [ Mac OS High Sierra ]

No problems in Code 1.30.2

**Comment by fuzzy76** [comment]
Latest css version
Latest standard vscode
OSS
macOS Mojave 10.14.3

**Comment by Spacebody** [comment]
Yes, I am using Mac.

**Visual Studio Code Version :** [ 1.31.0 ]
**Code Settings Sync Version :** [ 3.2.4 ]
**Standard or Insiders :** [ Standard ]
**OSS or Portable :** [ OSS ]
**Operating System :** [ Mac OS Mojava 10.14.3 ]

**Comment by shanalikhan** [comment]
>No problems in Code 1.30.2

@Spacebody  and @fuzzy76 

Try using 1.30.2 ?

**Comment by shanalikhan** [comment]
Anyway, thanks for reporting.

I use Linux and Windows to test Settings Sync.
Mac issues take time to solve till someone send PR or code fix in update.

**Comment by nekonenene** [comment]
It seems to be caused by chokidar. https://github.com/paulmillr/chokidar/issues/787
Update the dependency to latest(v2.1.0) may fix this problem.

**Comment by nekonenene** [comment]
I tried this change in my local Mac, but it does not resolve this problem, umm... 😢

**Comment by nekonenene** [comment]
https://github.com/Microsoft/vscode/issues/65335

> I have managed to resolve the issue by replacing the pre-built `fsevents` dependency with a newer version (v2, which uses N-API).

v2... i see...

**Comment by nekonenene** [comment]
I fixed this problem, but the verification is not enough.

https://github.com/nekonenene/code-settings-sync/commit/bd8c3dc6a123608d338c8be4941a76c078e3eb57

In addition, I don't know how to contribute to this repository yet. (Reading https://github.com/shanalikhan/code-settings-sync/wiki/Contributing ...)
So please wait for a while.

**Comment by Jvalal** [comment]
> I fixed this problem, but the verification is not enough.
> 
> [nekonenene@bd8c3dc](https://github.com/nekonenene/code-settings-sync/commit/bd8c3dc6a123608d338c8be4941a76c078e3eb57)
> 
> In addition, I don't know how to contribute to this repository yet. (I'm reading https://github.com/shanalikhan/code-settings-sync/wiki/Contributing now...)
> So please wait for a while.

would be great to know steps to resolve.

**Comment by fuzzy76** [comment]
Chokidar 2.1.0 released 4 days ago is supposed to have fixed it (by using a newer fsevents).

**Comment by nekonenene** [comment]
If you are macOS user and want to use Settings Sync right now, consider to install my patch.

**WARNING**: This patch overwrites v3.2.4. So, if you are trouble with this patch, you might want to reinstall official Settings Sync.

```sh
git clone https://github.com/nekonenene/code-settings-sync.git -b v3.2.4-patch && cd code-settings-sync
npm i
npm i -g vsce
vsce package
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension code-settings-sync-3.2.4.vsix

# Then, restart Visual Studio Code
```

**Comment by renannprado** [comment]
I havent tried fix of @nekonenene but I wonder if I'm having the same error.

![image](https://user-images.githubusercontent.com/2359543/52537608-e1397a80-2d68-11e9-859c-158997da30c3.png)

**Comment by nekonenene** [comment]
@renannprado Oh, it's other error. It is reported in https://github.com/shanalikhan/code-settings-sync/issues/765. (And I haven't seen this error...)

**Comment by jenkey2011** [comment]
Me too.

**Comment by msherrington** [comment]
I'm getting the exact same issue as the original poster. This occurred yesterday after updating to VSCode 1.31.1. I disabled all extensions and re-enabled them one-by-one to find the culprit is code-settings-sync.

🌴 **Visual Studio Code Version :** [ 1.31.1 ]
🌴 **Code Settings Sync Version :** [ 2.3.4 ]
🌴 **Standard or Insiders :** [ Standard ]
🌴 **OSS or Portable :** [ OSS ]
🌴 **Operating System :** [ MacOS Mojave 10.14.3 ]
🌴 **Occurs On:** [ Enabling the extension / Starting VSCode with the extension enabled / Restarting extension host ]

**Comment by baybird** [comment]
Having the same problem.

**Comment by cikichen** [comment]
Me too.

**Comment by shanalikhan** [comment]
v3.2.4 released with the fix by @nekonenene

Please update and let me know so i can close this ticket ?

**Comment by mbinkhorst** [comment]
Error is gone for me with the 3.2.5 update. Thanks all involved!

**Visual Studio Code Version :** [ 1.31.1 ]
**Code Settings Sync Version :** [ 3.2.5 ]
**Standard or Insiders :** [ Standard ]
**OSS or Portable :** [ OSS ]
**Operating System :** [ Mac OS High Sierra ]

**Comment by nekonenene** [comment]
Thanks for reporting!!!

**Comment by msherrington** [comment]
Working again. Thank you!

**Comment by Spacebody** [comment]
Okay, the problem had been solved.

**Comment by baybird** [comment]
Found a better one 'Syncing'. Save my day.
