### PR TITLE
Avoid using chokidar (Fix #762)

### LINKED ISSUE #762: Not working with VSCode 1.31
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version :** [ 1.31 ] 
🌴 **Code Settings Sync Version :** [ 2.3.4 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ Mac OS High Sierra ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]

📰 **To Reproduce**
1. Update VSCode to 1.31
2. Start VSCode
3. See error

💪 **Expected behavior**
Working like it does all time.

📺 **Console Error Log** 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/yannheeser/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/yannheeser/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

📺  **Additional context**

"Extension host terminated unexpectedly"

### PR DESCRIPTION
**Pull request by nekonenene**
#### Short description of what this resolves:

Fix "Extension host terminated unexpectedly" in Visual Studio Code v1.31.0 with Settings Sync.
( https://github.com/Microsoft/vscode/issues/64981 )

sc 617

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/xxx/.vscode/extensions/shan.code-settings-sync-3.2.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

It causes by `fsevents`, also `chokidar`.
https://github.com/Microsoft/vscode/issues/65335

So, I remove `chokidar` from this repository, and use **[FileSystemWatcher](https://vshaxe.github.io/vscode-extern/vscode/FileSystemWatcher.html)** .

Thanks: https://github.com/fabiospampinato/vscode-projects-plus/commit/8357ab76b9d600802c71777f280b76240765da48#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

#### Changes proposed in this pull request:

- Remove chokidar
    - disable depth setting because use FileSystemWatcher (sorry...)
- Update install_local.txt

**Fixes**: #762 

#### How Has This Been Tested?

* Put `console.log` to check if pass through StartWatch, onDidChange, CloseWatch.
* Update locale.json (vscode setting), and see starting to upload. Check the gist file if update correctly.
* Update that 5 times, and every upload successfully finished.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [ ] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

File: src/commons.ts [hunk 1]
```diff
@@ -97,14 +96,12 @@ export default class Commons {
     }
 
     let uploadStopped: boolean = true;
-    Commons.extensionWatcher = chokidar.watch(this.en.ExtensionFolder, {
-      depth: 0,
-      ignoreInitial: true
-    });
-    Commons.configWatcher = chokidar.watch(this.en.PATH + "/User/", {
-      depth: 2,
```
Comment (shanalikhan) [inline src/commons.ts]: How are you handling the `depth` as 2 in File System Watcher

File: src/commons.ts [hunk 2]
```diff
@@ -97,14 +96,12 @@ export default class Commons {
     }
 
     let uploadStopped: boolean = true;
-    Commons.extensionWatcher = chokidar.watch(this.en.ExtensionFolder, {
-      depth: 0,
-      ignoreInitial: true
-    });
-    Commons.configWatcher = chokidar.watch(this.en.PATH + "/User/", {
-      depth: 2,
-      ignoreInitial: true
```
Comment (shanalikhan) [inline src/commons.ts]: It would be great if you can write details how are you handling these situations on `FileSystemWatcher`

File: src/commons.ts (hunk 1 above)
Comment (nekonenene) [reply src/commons.ts]: You mean the watcher should not watch under directories in `workspaceStorage`.
OK, I'll try handling it! Thanks.

File: src/commons.ts (hunk 2 above)
Comment (nekonenene) [reply src/commons.ts]: The watcher doesn't watch the `add` event now, so I think it's not problem to ignore this option.

File: src/commons.ts (hunk 1 above)
Comment (nekonenene) [reply src/commons.ts]: @shanalikhan 
Fixed by https://github.com/shanalikhan/code-settings-sync/pull/763/commits/758baf7007fc66be3833243d20e927efba39f606
But it's not beautiful way... umm...

**Comment by fuzzy76** [comment]
A much easier fix would be to bump chokidar to 2.1.0, as the problem is fixed.

File: src/commons.ts (hunk 2 above)
Comment (nekonenene) [reply src/commons.ts]: Now, I checked this behavior.
FileSystemWatcher and chokidar with `ignoreInitial: true` are same. 😄 

Add the following code for check, and `Added: ` logs are not appeared when the window reloads.

```ts
    Commons.configWatcher.onDidCreate(async (uri: vscode.Uri) => {
      const path: string = uri.path;
      console.log("Added: " + path);
    });
```

I also checked the case of `ignoreInitial: false`. https://github.com/nekonenene/code-settings-sync/commit/59412864cff08cc078d2f4aec7584a10c0e3eb5d

sc 619

**Comment by nekonenene** [comment]
@fuzzy76 
Did you rebuild and install code-settings-sync, and launch Visual Studio Code 1.31.0?
I already tried, and it causes the error sadly.

**Comment by shanalikhan** [comment]
It would personally recommend using vscode own file change events rather chokidar, when i developed this feature there were no api developed by code team thats why Settings Sync is using chokidar itself.

If new update of chokidar fix this problem, send new PR and i will accept that to push new version.
Meanwhile, i will test it and merge it soon.

**Comment by nekonenene** [comment]
@shanalikhan Thanks! So, should i close this PR?

**Comment by shanalikhan** [comment]
No, Keep this open, I will merge it soon.

**Comment by nekonenene** [comment]
Oh, I misunderstood your comment.

I hope that `fsevents` will update, and merge to `chokidar`. Thank you for merge.

**Comment by nekonenene** [comment]
Note: chokidar v2.1.1 is released yesterday, but, it includes fsevents v1.2.7 same as v2.1.0. I tried v2.1.1, and error occured.
